import scipy.linalg
import utils
import sys
import numpy as np
import random
import subprocess
import statistics
from numpy.linalg import LinAlgError, inv
import pathlib
import matplotlib.pyplot as plt
import scipy
import time
import os
import pickle
import tempfile
import traceback


# === Load Pickled Datasets ===
def load_datasets(directory):
    datasets = {}
    for filename in sorted(os.listdir(directory)):
        if filename.endswith(".pkl"):
            path = os.path.join(directory, filename)
            with open(path, "rb") as f:
                datasets[filename.replace(".pkl", "")] = pickle.load(f)
    return datasets['all_datasets']


# === L1 Lower Bound ===
def l1_bound(items: np.ndarray, capacity: int) -> float:
    # This is a simple lower bound for the bin packing problem, as described
    # in the FunSearch paper. It is the sum of the item sizes divided by the
    # bin capacity, rounded up to the nearest integer.
    return np.ceil(np.sum(items) / capacity)


def l1_bound_dataset(instances: list) -> float:
    return np.mean([
        l1_bound(instance['Items']['Size'].to_numpy(),
                 instance['Bin Capacity']) for instance in instances
    ])


# === Online Bin Packing Helper ===
def get_valid_bin_indices(item: float, bins: np.ndarray) -> np.ndarray:
    return np.nonzero((bins - item) >= 0)[0]


class g:
    pass


def create_function_from_string(function_code):
    exec(function_code, globals())
    return priority


# === Evaluate Graph Using Global train_instances ===
def evaluate_graph(predict: str) -> float:
    # This function evaluates a given program (in the form of a Python string)
    # on the training instances. This is the "evaluator" component of FunSearch.
    # See CITATIONS.md for the full reference to the FunSearch paper.
    # The program is executed in a separate process to prevent it from
    # interfering with the main process.
    instances = train_instances
    opt_bins = train_l1
    #print("[evaluate_graph] Predict function:\n", predict)
    try:
        with tempfile.NamedTemporaryFile(mode='w', suffix='.py',
                                         delete=False) as code_file:
            code_file.write(predict)
            code_file.flush()

        with tempfile.NamedTemporaryFile(mode='wb',
                                         suffix='.pkl',
                                         delete=False) as data_file:
            pickle.dump((instances, opt_bins), data_file)
            data_file.flush()

        eval_script = """
import sys
import numpy as np
import pickle
import traceback

def create_function(path):
    with open(path, 'r') as f:
        code = f.read()
    local_vars = {}
    global_vars = {"np": __import__("numpy")}
    exec(code, global_vars, local_vars)
    return local_vars['priority']

def evaluate(instances, priority_fn):
    # This is the core evaluation function. It takes a set of bin packing
    # instances and a priority function, and returns the average number of
    # bins used. The priority function is the program generated by the LLM.
    def get_valid_bin_indices(item, bins):
        return np.nonzero((bins - item) >= 0)[0]
    def online_binpack(items, bins, priority_fn):
        packing = [[] for _ in bins]
        for item in items:
            valid = get_valid_bin_indices(item, bins)
            if len(valid) == 0:
                continue
            scores = priority_fn(item, bins[valid])
            best = valid[np.argmax(scores)]
            bins[best] -= item
            packing[best].append(item)
        return packing, bins
    num_bins = []
    for instance in instances:
        try:
            items = instance['Items']['Size'].to_numpy()
            capacity = instance['Bin Capacity']
            bins = np.array([capacity] * len(items))
            _, bins_packed = online_binpack(items, bins, priority_fn)
            used_bins = (bins_packed != capacity).sum()
            num_bins.append(used_bins)
        except:
            pass
    return -np.mean(num_bins)

try:
    code_path, data_path = sys.argv[1], sys.argv[2]
    with open(data_path, 'rb') as f:
        instances, opt_bins = pickle.load(f)

    if opt_bins is None or opt_bins <= 0 or np.isnan(opt_bins) or np.isinf(opt_bins):
        raise ValueError("Invalid opt_bins")

    fn = create_function(code_path)
    avg_bins = -evaluate(instances, fn)

    if np.isnan(avg_bins):
        raise ValueError("avg_bins is NaN")

    excess = (avg_bins - opt_bins) / opt_bins

    if np.isnan(excess):
        raise ValueError("excess is NaN")

    print(100 * excess)

except:
    print(float('inf'))
"""

        with tempfile.NamedTemporaryFile(mode='w', suffix='.py',
                                         delete=False) as eval_file:
            eval_file.write(eval_script)
            eval_file.flush()

        process = subprocess.run(
            [sys.executable, eval_file.name, code_file.name, data_file.name],
            stderr=subprocess.PIPE,
            stdout=subprocess.PIPE,
            timeout=60)

        result_str = process.stdout.decode().strip()
        stderr_output = process.stderr.decode().strip()

        #print("[evaluate_graph] Subprocess stderr:\n", stderr_output)
        #print("[evaluate_graph] Subprocess stdout:\n", result_str)

        try:
            result = float(result_str)
            #print(f"[evaluate_graph] Final result: {result}", flush=True)
            if not np.isfinite(result):
                raise ValueError("Result is NaN or Inf")
            return result
        except Exception as parse_err:
            #print(f"[evaluate_graph] Failed to parse result: {result_str!r} ({parse_err})", file=sys.stderr)
            return float('inf')

    except subprocess.TimeoutExpired:
        #print("[evaluate_graph] Subprocess timed out!", file=sys.stderr)
        return float('inf')
    except Exception as e:
        #print(f"[evaluate_graph] Unexpected error: {e}", file=sys.stderr)
        traceback.print_exc()
        return float('inf')
    finally:
        for path in [code_file.name, data_file.name, eval_file.name]:
            try:
                os.unlink(path)
            except Exception:
                pass


# === Load Datasets and Globals ===
with open("train_instances.pkl", "rb") as f:
    train_instances = pickle.load(f)

with open("val_instances.pkl", "rb") as f:
    val_instances = pickle.load(f)

instances = train_instances
train_l1 = l1_bound_dataset(train_instances)
opt_bins = train_l1

# === Example Evaluation ===
predict = """
def priority(item: float, bins: np.ndarray) -> np.ndarray:
    return -(bins - item)
"""

evaluate_graph(predict)
